export const executives = [
    {
        imageURL: "https://lh3.googleusercontent.com/sitesv/APaQ0SQMTF_Ok6wUgr9UoPaNmcEeJ1lMaCYXHxps7OXoCt9LpwWO4OwqTPcq0-9BdsLrlYx6zDlkxXzOpsKnVhVdZfvlHEKmr9Q6GkJ6866WnxnL0Xnm7YVhkv8x1SfGkhiZfZj5Zke8IV7lsn2c5KFp8MqoxuD1crLDOz-vF6nrwe-OmM9bSCDA7KOAtmfd6f3B5Gu6sE9CSM0HA_4yx_eaCtswkDC1GJsT31E6LGY=w1280",
        displayName: "Chris",
        role: "Co-President Executive",
        description: "One of the big bosses of KAC, Chris! He not only leads the team but checks in with our progress and makes sure everything is up to code 📋 When he’s not making sure we’re locked in, he’s probably out there snipping with his camera 📸 to create new stickers of the team on Instagram 😓 If you see him around campus with his airpods on, chances are he’s blasting EDM to lock in 🎶",
        fullName: "Christopher Tjong",
        ethnicity: "Chinese-Indonesian 🇨🇳🇮🇩",
        degree: "Bachelor of Commerce in Economics and Finance",
        mbti: "INFJ",
        fact: "D1 IC2 Dweller",
        sponsor: "Kompass",
        greenFlag: "I am always down to eat",
        redFlag: "Grandpa sleep schedule ",
        emojis: "🫩🫡 😵‍💫",
    },
    {
        imageURL: "https://lh3.googleusercontent.com/sitesv/APaQ0STtmPNlK_LSiGasxC-aot-rI7TJzdm6U432CY9KN4Ws2gB615lDqOlrYFyvTSD9qyiLacKIGyeUGlriqQpUi0dhjO1c3V8bRHxBSgdkPLAuP8HvEUdI0Xit2ktn2hwEgm-KK1J-N_wGXQSrMydPn6rpljXm2wOmOyC2fbYoSUBfmRCsb95ACzQ0qmY_8Wzq-Fu5q1ZGutAkkUAb6O99fD5czYbk5kjIFPbcMMg=w1280",
        displayName: "Jimmy",
        role: "Co-President Executive",
        description: "Another big boss of KAC, Jimmy! Helping to steer the team when we’re off track and making sure everything goes smoothly! Whether it's handling day-to-day tasks or keeping the vibe upbeat, Jimmy’s always on top of it 👏 He’s the life of the party, always bringing laughter and fun to every situation 🥳 If you bring up his Miata, get ready for the yap 🚗It’s freaking awesome 🔥",
        fullName: "Jimmy Li",
        ethnicity: "Chinese 🇨🇳",
        degree: "Bachelor of Arts",
        mbti: "ENFJ",
        fact: "Can 1 bite a cheeseburger",
        sponsor: "Chubby Boy",
        greenFlag: "Always has music recommendations",
        redFlag: "RBF",
        emojis: "🤙",
    },
    {
        imageURL: "https://lh3.googleusercontent.com/sitesv/APaQ0ST1912aJ6x5apb7t5a4BmKmYTRAr_sfhk0ZLwkhz8tEqcjrSjDtWEMlin0Bgd5xiVo0-u5V5xopL6X30Ld-KEPtMpZdYasIducWIZfTQ7xPUatyw9z7JuNYQh0ylYfhTxhJykq3MhOyJlDUG8U_1Fx3wfyE5hJV8KRytp-laJ3Ktigq0A29VovecvLQbCQDcbvxnzHrmaB4HBL8HiAN20F7G1AfHQI3o_l6=w1280",
        displayName: "Kaco",
        role: "Mascot",
        description: "Kaco is back! With a brand new look to start the year, he’s the heart of our team ❤️‍🔥 You’ll catch him in basically all our marketing - always modelling for shoots, always camera-ready, and never missing his moment 📸✨ Kaco stays locked in for the team, holding it down behind the scenes and showing up whenever we need him 🫡 A certified big back who’s always down for a munch, so don’t be surprised if your food mysteriously goes missing 🍱😆",
        fullName: "Kaco Big-Backo",
        ethnicity: "",
        degree: "",
        mbti: "",
        fact: "Was born in the year of the dragon 🐉",
        sponsor: "Kompass",
        greenFlag: "Always down for an adventure",
        redFlag: "Can accidentally breathe fire if he’s too excited",
        emojis: "",
    },
    {
        imageURL: "https://lh3.googleusercontent.com/sitesv/APaQ0STeoEFJwEXsL1d_XGmeH2FKySigL5CsHFZQjCAsPNBAgyHYvw3WAG8ksxk68eqdguTkuBJnLyD6IcMnMRfHo0IPTohkNDjQ0SE1IS9z6_YGmp70JVlV32rS3spgZcFqJIZ0fr5sCnZ6l5kn7wbrAen-W7_8Fg9dR5qe7mt9gx9-z5bO-YBwYXJ052SrfiAScyauqFur-jUD1_hNZsjizoKgBuWkH8n50l8a=w1280",
        displayName: "Edison",
        role: "Treasurer Executive",
        description: "Edison is responsible for overseeing KAC’s finances 👏He ensures we have the necessary budget to host all our events! 💸 When he’s not managing the numbers, he’s probably being a sweat on Roblox or being dragged to his 10th Malatang of the week 🍲",
        fullName: "Edison Ye",
        ethnicity: "Chinese 🇨🇳",
        degree: "Accounting & Finance",
        mbti: "ISTJ",
        fact: "My nose bleeds easily",
        sponsor: "The Don",
        greenFlag: "CRACKED at roblox gaming (is this even a green flag)",
        redFlag: "Indecisive eater",
        emojis: "🦭",
    },
]